export const unitopJSONData = [
  {
    label: "Cartridge Filter",
    slug: "cartridgeFilter",
    region: "NAM",
    packagedSystemFirmProposal: true,
    // icon: cartridge,
    model: [
      {
        label: "HX0730-3.0F-316-A Non Code Stamped",
        value: "HX0730-3.0F-316-A Non Code Stamped",
        auto_size: "110",
        recovery: 0.9,
      },
      {
        label: "HX0740-3.0F-316-A Non Code Stamped",
        value: "HX0740-3.0F-316-A Non Code Stamped",
        auto_size: "150",
        recovery: 1,
      },
      {
        label: "S6EF12-3-3F-SW-IP Non-Code Stamped",
        value: "S6EF12-3-3F-SW-IP Non-Code Stamped",
        auto_size: "180",
        recovery: 1,
      },
      {
        label: "S6GL12-012-3-3F-IP Code Stamped",
        value: "S6GL12-012-3-3F-IP Code Stamped",
        auto_size: "240",
        recovery: 1,
      },
      {
        label: "S6GL16-025-4-4F-IP Code Stamped",
        value: "S6GL16-025-4-4F-IP Code Stamped",
        auto_size: "440",
        recovery: 1,
      },
      {
        label: "S6EF25-4-4F-SW-IP Non Code Stamped",
        value: "S6EF25-4-4F-SW-IP Non Code Stamped",
        auto_size: "500",
        recovery: 1,
      },
      {
        label: "S6EF52-4-8F-IP Non Code Stamped",
        value: "S6EF52-4-8F-IP Non Code Stamped",
        auto_size: "1040",
        recovery: 1,
      },
      {
        label: "S6GL22-052-4-8F-IP Code Stamped",
        value: "S6GL22-052-4-8F-IP Code Stamped",
        auto_size: "1060",
        recovery: 1,
      },
      {
        label: "S6EF142-4-12F-IP Non Code Stamped",
        value: "S6EF142-4-12F-IP Non Code Stamped",
        auto_size: "2840",
        recovery: 1,
      },
      {
        label: "S6GL36-142-4-12F-IP Code Stamped",
        value: "S6GL36-142-4-12F-IP Code Stamped",
        auto_size: "2920",
        recovery: 1,
      },
    ],
  },
  {
    label: "CIP",
    slug: "CIP",
    region: "NAM",
    packagedSystemFirmProposal: true,
    model: [
      {
        label: "SeaPRO-CIP-84 60 Hz",
        value: "SeaPRO-CIP-84 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-84 50 Hz",
        value: "SeaPRO-CIP-84 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-8 60 Hz",
        value: "SeaPRO-CIP-8 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-8 50 Hz",
        value: "SeaPRO-CIP-8 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-63 60 Hz",
        value: "SeaPRO-CIP-63 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-63 50 Hz",
        value: "SeaPRO-CIP-63 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-42 60 Hz",
        value: "SeaPRO-CIP-42 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-42 50 Hz",
        value: "SeaPRO-CIP-42 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-24/28 60 Hz",
        value: "SeaPRO-CIP-24/28 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-24/28 50 Hz",
        value: "SeaPRO-CIP-24/28 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-16 60 Hz",
        value: "SeaPRO-CIP-16 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-16 50 Hz",
        value: "SeaPRO-CIP-16 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-126 60 Hz",
        value: "SeaPRO-CIP-126 60 Hz",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "SeaPRO-CIP-126 50 Hz",
        value: "SeaPRO-CIP-126 50 Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 90-108 CIP",
        value: "PROflex 90-108 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 72-81 CIP",
        value: "PROflex 72-81 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 42-54 CIP",
        value: "PROflex 42-54 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 30-36 CIP",
        value: "PROflex 30-36 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 18-24 CIP",
        value: "PROflex 18-24 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "PROflex 12 CIP",
        value: "PROflex 12 CIP",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-68-480V",
        value: "CIP-PRO-LA-68-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-68-380V",
        value: "CIP-PRO-LA-68-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-45-480V",
        value: "CIP-PRO-LA-45-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-45-380V",
        value: "CIP-PRO-LA-45-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-34-480V",
        value: "CIP-PRO-LA-34-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-34-380V",
        value: "CIP-PRO-LA-34-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-23-480V",
        value: "CIP-PRO-LA-23-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-23-380V",
        value: "CIP-PRO-LA-23-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-11-480V",
        value: "CIP-PRO-LA-11-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-11-380V",
        value: "CIP-PRO-LA-11-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-102-480V",
        value: "CIP-PRO-LA-102-480V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-LA-102-380V",
        value: "CIP-PRO-LA-102-380V",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-68-EU-BAS",
        value: "CIP-PRO-68-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-45-EU-BAS",
        value: "CIP-PRO-45-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-34-EU-BAS",
        value: "CIP-PRO-34-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-23-EU-BAS",
        value: "CIP-PRO-23-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-11-EU-BAS",
        value: "CIP-PRO-11-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-PRO-102-EU-BAS",
        value: "CIP-PRO-102-EU-BAS",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-E-Series-CE 380VAC/50Hz",
        value: "CIP-E-Series-CE 380VAC/50Hz",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-50 Individual Stage Cleaning",
        value: "CIP-50 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-450 Individual Stage Cleaning",
        value: "CIP-450 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-300 Individual Stage Cleaning",
        value: "CIP-300 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-200 Individual Stage Cleaning",
        value: "CIP-200 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-150 Individual Stage Cleaning",
        value: "CIP-150 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-100 Individual Stage Cleaning",
        value: "CIP-100 Individual Stage Cleaning",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP TITAN-90",
        value: "CIP TITAN-90",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP TITAN-36/72",
        value: "CIP TITAN-36/72",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP TITAN-180",
        value: "CIP TITAN-180",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP TITAN-144",
        value: "CIP TITAN-144",
        auto_size: "",
        frequency_family: "60Hz",
        cIPType_model: "Standard",
      },
      {
        label: "CIP-BEV-100 Basic",
        value: "CIP-BEV-100 Basic",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-100 Premium",
        value: "CIP-BEV-100 Premium",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-150 Basic",
        value: "CIP-BEV-150 Basic",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-150 Premium",
        value: "CIP-BEV-150 Premium",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-250 Basic",
        value: "CIP-BEV-250 Basic",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-250 Premium",
        value: "CIP-BEV-250 Premium",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-300 Basic",
        value: "CIP-BEV-300 Basic",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-300 Premium",
        value: "CIP-BEV-300 Premium",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-300X2 Basic",
        value: "CIP-BEV-300X2 Basic",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP-BEV-300X2 Premium",
        value: "CIP-BEV-300X2 Premium",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 18-24 CIP-SKID",
        value: "PROflex 18-24 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 30-36 CIP-SKID",
        value: "PROflex 30-36 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 42-54 CIP-SKID",
        value: "PROflex 42-54 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 72-81 CIP-SKID",
        value: "PROflex 72-81 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 90-108 CIP-SKID",
        value: "PROflex 90-108 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "PROflex 12 CIP-SKID",
        value: "PROflex 12 CIP-SKID",
        auto_size: "",
        cIPType_model: "Custom",
        frequency_family: "60Hz",
      },
      {
        label: "CIP PRO ECELL EU-50HZ",
        value: "CIP PRO ECELL EU-50HZ",
        auto_size: "",
        frequency_family: "50Hz",
        cIPType_model: "Custom",
      },
    ],
  },
  {
    label: "Chemical Feed",
    slug: "chemicalFeed",
    region: "NAM,EMEA",
    packagedSystemFirmProposal: true,
    model: [
      { label: "Antiscalant", value: "Antiscalant", auto_size: "" },
      { label: "Biocide", value: "Biocide", auto_size: "" },
      { label: "Citric Acid", value: "Citric Acid", auto_size: "" },
      { label: "Ferric Chloride", value: "Ferric Chloride", auto_size: "" },
      { label: "Filter Aid", value: "Filter Aid", auto_size: "" },
      {
        label: "Hydrochoric Acid 32%",
        value: "Hydrochoric Acid 32%",
        auto_size: "",
      },
      {
        label: "Potassium Permanganate",
        value: "Potassium Permanganate",
        auto_size: "",
      },
      { label: "Sodium Bisulilte", value: "Sodium Bisulilte", auto_size: "" },
      {
        label: "Sodium Hydroxide 25%",
        value: "Sodium Hydroxide 25%",
        auto_size: "",
      },
      {
        label: "Sodium Hydroxide 50%",
        value: "Sodium Hydroxide 50%",
        auto_size: "",
      },
      {
        label: "Sodium Hypochlorite",
        value: "Sodium Hypochlorite",
        auto_size: "",
      },
      {
        label: "Sulfuric Acid < 70%",
        value: "Sulfuric Acid < 70%",
        auto_size: "",
      },
      {
        label: "Sulfuric Acid < 96%",
        value: "Sulfuric Acid < 96%",
        auto_size: "",
      },
    ],
  },
  {
    label: "Distribution Pump",
    slug: "distributionPump",
    region: "NAM",
    packagedSystemFirmProposal: true,
    model: [
      {
        label: "Flowserve (50 gpm @ 65psi)",
        value: "Flowserve (50 gpm @ 65psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (100 gpm @ 65psi)",
        value: "Flowserve (100 gpm @ 65psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (150 gpm @ 65psi)",
        value: "Flowserve (150 gpm @ 65psi)",
        auto_size: "150",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (200 gpm @ 65psi)",
        value: "Flowserve (200 gpm @ 65psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (300 gpm @ 65psi)",
        value: "Flowserve (300 gpm @ 65psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (400 gpm @ 65psi)",
        value: "Flowserve (400 gpm @ 65psi)",
        auto_size: "450",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (500 gpm @ 65psi)",
        value: "Flowserve (500 gpm @ 65psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (750 gpm @ 65psi)",
        value: "Flowserve (750 gpm @ 65psi)",
        auto_size: "750",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (1000 gpm @ 65psi)",
        value: "Flowserve (1000 gpm @ 65psi)",
        auto_size: "1000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (1500 gpm @ 65psi)",
        value: "Flowserve (1500 gpm @ 65psi)",
        auto_size: "1500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Flowserve (2000 gpm @ 65psi)",
        value: "Flowserve (2000 gpm @ 65psi)",
        auto_size: "2000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K1.5x1-8 2RV M3 ST 1 (100 gpm @60psi)",
        value: "1K1.5x1-8 2RV M3 ST 1 (100 gpm @60psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K1.5x1-8 2RV M3 ST 1 (200 gpm @80psi)",
        value: "1K1.5x1-8 2RV M3 ST 1 (200 gpm @80psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K3x2-8 2RV M3 ST 1 (300 gpm @70psi)",
        value: "2K3x2-8 2RV M3 ST 1 (300 gpm @70psi)",
        auto_size: "300",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K4x3-8 2RV M3 ST 1 (400 gpm @80psi)",
        value: "2K4x3-8 2RV M3 ST 1 (400 gpm @80psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K4x3-8 2RV M3 ST 1 (500 gpm @80psi)",
        value: "2K4x3-8 2RV M3 ST 1 (500 gpm @80psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 RV M3 ST 1 (700 gpm @80psi)",
        value: "2K6x4-10 RV M3 ST 1 (700 gpm @80psi)",
        auto_size: "700",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 RV M3 ST 1 (1000 gpm @80psi)",
        value: "2K6x4-10 RV M3 ST 1 (1000 gpm @80psi)",
        auto_size: "1000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K8x6-14 ARV M3 ST 1 (2000 gpm @80psi)",
        value: "3K8x6-14 ARV M3 ST 1 (2000 gpm @80psi)",
        auto_size: "2000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K3x1.5-6 2RV M3 ST 1 (100 gpm @20psi)",
        value: "1K3x1.5-6 2RV M3 ST 1 (100 gpm @20psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K3x2-6 2RV M3 ST 1 (200 gpm @20 psi)",
        value: "1K3x2-6 2RV M3 ST 1 (200 gpm @20 psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K4x3-8 2RV M3 ST 1 (400 gpm @30psi)",
        value: "2K4x3-8 2RV M3 ST 1 (400 gpm @30psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 RV M3 ST 1 (500 gpm @20psi)",
        value: "2K6x4-10 RV M3 ST 1 (500 gpm @20psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 HRV M3 ST 1 (700 gpm @20psi)",
        value: "2K6x4-10 HRV M3 ST 1 (700 gpm @20psi)",
        auto_size: "700",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 HRV M3 ST 1 (1000 gpm @40psi)",
        value: "2K6x4-10 HRV M3 ST 1 (1000 gpm @40psi)",
        auto_size: "1000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K8x6-16 ARV M3 ST 1 (2000 gpm @30psi)",
        value: "3K8x6-16 ARV M3 ST 1 (2000 gpm @30psi)",
        auto_size: "2000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K10x8-14 RV M3 ST 1 (3000 gpm @20psi)",
        value: "3K10x8-14 RV M3 ST 1 (3000 gpm @20psi)",
        auto_size: "3000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K1.5x1-6 2RV M3 ST 1 (50 gpm @60psi)",
        value: "1K1.5x1-6 2RV M3 ST 1 (50 gpm @60psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K3x1.5-6 2RV M3 ST 1 (100 gpm @20psi)",
        value: "1K3x1.5-6 2RV M3 ST 1 (100 gpm @20psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "1K3x1.5-6 2RV M3 ST 1 (200 gpm @60psi)",
        value: "1K3x1.5-6 2RV M3 ST 1 (200 gpm @60psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K3x2-8 2RV M3 ST 1 (300 gpm @70psi)",
        value: "2K3x2-8 2RV M3 ST 1 (300 gpm @70psi)",
        auto_size: "300",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K4x3-8 2RV M3 ST 1 (400 gpm @70psi)",
        value: "2K4x3-8 2RV M3 ST 1 (400 gpm @70psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K4x3-8 2RV M3 ST 1 (500 gpm @80psi)",
        value: "2K4x3-8 2RV M3 ST 1 (500 gpm @80psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "2K6x4-10 RV M3 ST 1 (1000 gpm @70psi)",
        value: "2K6x4-10 RV M3 ST 1 (1000 gpm @70psi)",
        auto_size: "1000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K8x6-14 ARV M3 ST 1 (2000 gpm @60psi)",
        value: "3K8x6-14 ARV M3 ST 1 (2000 gpm @60psi)",
        auto_size: "2000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K10x8-14 RV (3000 gpm @50psi)",
        value: "3K10x8-14 RV (3000 gpm @50psi)",
        auto_size: "3000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "3K10x8 -16HRV (6000 gpm @50psi)",
        value: "3K10x8 -16HRV (6000 gpm @50psi)",
        auto_size: "6000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "4K16x16-18OP (10000 gpm @50psi)",
        value: "4K16x16-18OP (10000 gpm @50psi)",
        auto_size: "10000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (50 gpm @ 69psi)",
        value: "Alpha-Laval LKH (50 gpm @ 69psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (80 gpm @ 70psi)",
        value: "Alpha-Laval LKH (80 gpm @ 70psi)",
        auto_size: "80",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (200 gpm @ 70psi)",
        value: "Alpha-Laval LKH (200 gpm @ 70psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (400 gpm @ 70psi)",
        value: "Alpha-Laval LKH (400 gpm @ 70psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (1100 gpm @ 70psi)",
        value: "Alpha-Laval LKH (1100 gpm @ 70psi)",
        auto_size: "1100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Alpha-Laval LKH (1700 gpm @ 70psi)",
        value: "Alpha-Laval LKH (1700 gpm @ 70psi)",
        auto_size: "1700",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (50 gpm @ 65psi)",
        value: "Goulds (50 gpm @ 65psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (130 gpm @ 65psi)",
        value: "Goulds (130 gpm @ 65psi)",
        auto_size: "130",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (160 gpm @ 65psi)",
        value: "Goulds (160 gpm @ 65psi)",
        auto_size: "160",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (225 gpm @ 65psi)",
        value: "Goulds (225 gpm @ 65psi)",
        auto_size: "225",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (320 gpm @ 65psi)",
        value: "Goulds (320 gpm @ 65psi)",
        auto_size: "320",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (380 gpm @ 65psi)",
        value: "Goulds (380 gpm @ 65psi)",
        auto_size: "380",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (640 gpm @ 65psi)",
        value: "Goulds (640 gpm @ 65psi)",
        auto_size: "640",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Goulds (770 gpm @ 65psi)",
        value: "Goulds (770 gpm @ 65psi)",
        auto_size: "770",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (111 gpm @69psi)",
        value: "Grundfos CRN (111 gpm @69psi)",
        auto_size: "111.4",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (200 gpm @85psi)",
        value: "Grundfos CRN (200 gpm @85psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (300 gpm @80psi)",
        value: "Grundfos CRN (300 gpm @80psi)",
        auto_size: "300",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (400 gpm @87psi)",
        value: "Grundfos CRN (400 gpm @87psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (500 gpm @84psi)",
        value: "Grundfos CRN (500 gpm @84psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (200 gpm @35psi)",
        value: "Grundfos CRN (200 gpm @35psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (400 gpm @35psi)",
        value: "Grundfos CRN (400 gpm @35psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (100 gpm @23psi)",
        value: "Grundfos CRN (100 gpm @23psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (700 gpm @29psi)",
        value: "Grundfos CRN (700 gpm @29psi)",
        auto_size: "700",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (50 gpm @65psi)",
        value: "Grundfos CRN (50 gpm @65psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (100 gpm @40psi)",
        value: "Grundfos CRN (100 gpm @40psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (200 gpm @70psi)",
        value: "Grundfos CRN (200 gpm @70psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (400 gpm @75psi)",
        value: "Grundfos CRN (400 gpm @75psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Grundfos CRN (500 gpm @85psi)",
        value: "Grundfos CRN (500 gpm @85psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "SV 407 N11T (22 m3/h @58 bar)",
        value: "SV 407 N11T (22 m3/h @58 bar)",
        auto_size: "22",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "SV 804 N22T (40 m3/h @58 bar)",
        value: "SV 804 N22T (40 m3/h @58 bar)",
        auto_size: "40",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "SV 1603 N30T (57 m3/h @58 bar)",
        value: "SV 1603 N30T (57 m3/h @58 bar)",
        auto_size: "57",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 32-200/40 (66 m3/h @58 bar)",
        value: "FHE 32-200/40 (66 m3/h @58 bar)",
        auto_size: "66",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 32-250/75 (66 m3/h @101 bar)",
        value: "FHE 32-250/75 (66 m3/h @101 bar)",
        auto_size: "66",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 40-200/55 (132 m3/h @58 bar)",
        value: "FHE 40-200/55 (132 m3/h @58 bar)",
        auto_size: "132",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 40-250/150 (132 m3/h @101 bar)",
        value: "FHE 40-250/150 (132 m3/h @101 bar)",
        auto_size: "132",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 40-200/75 (198 m3/h @58 bar)",
        value: "FHE 40-200/75 (198 m3/h @58 bar)",
        auto_size: "198",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 50-250/185 (198 m3/h @101 bar)",
        value: "FHE 50-250/185 (198 m3/h @101 bar)",
        auto_size: "198",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 50-200/92 (264 m3/h @58 bar)",
        value: "FHE 50-200/92 (264 m3/h @58 bar)",
        auto_size: "264",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHE 65-200/150 (396 m3/h @58 bar)",
        value: "FHE 65-200/150 (396 m3/h @58 bar)",
        auto_size: "396",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHS 65-250/300 (396 m3/h @101 bar)",
        value: "FHS 65-250/300 (396 m3/h @101 bar)",
        auto_size: "396",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "FHE 80-200/220 (572 m3/h @58 bar)",
        value: "FHE 80-200/220 (572 m3/h @58 bar)",
        auto_size: "572",
        recovery: 1,
        frequency_family: "50Hz",
      },
      {
        label: "FHS 80-250/450 (572 m3/h @101 bar)",
        value: "FHS 80-250/450 (572 m3/h @101 bar)",
        auto_size: "572",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "FM-4X5-8 (500 gpm @20psi)",
        value: "FM-4X5-8 (500 gpm @20psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "FM-3X4-8A (700 gpm @80psi)",
        value: "FM-3X4-8A (700 gpm @80psi)",
        auto_size: "700",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (50 gpm @60psi)",
        value: "Summit ANSI (50 gpm @60psi)",
        auto_size: "50",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (100 gpm @60psi)",
        value: "Summit ANSI (100 gpm @60psi)",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (200 gpm @60psi)",
        value: "Summit ANSI (200 gpm @60psi)",
        auto_size: "200",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (300 gpm @70psi)",
        value: "Summit ANSI (300 gpm @70psi)",
        auto_size: "300",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (400 gpm @70psi)",
        value: "Summit ANSI (400 gpm @70psi)",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (500 gpm @80psi)",
        value: "Summit ANSI (500 gpm @80psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (500 gpm @80psi)",
        value: "Summit ANSI (500 gpm @80psi)",
        auto_size: "500",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (1000 gpm @70psi)",
        value: "Summit ANSI (1000 gpm @70psi)",
        auto_size: "1000",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Summit ANSI (1500 gpm @ 70 psi)",
        value: "Summit ANSI (1500 gpm @ 70 psi)",
        auto_size: "1500",
        recovery: 1,
        frequency_family: "60Hz",
      },
    ],
  },
  {
    label: "UV Light",
    slug: "uvLight",
    region: "NAM",
    packagedSystemFirmProposal: true,
    model: [
      {
        label: "Optivenn",
        value: "Optivenn",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquafine/Trojan",
      },
      {
        label: "UVLogic",
        value: "UVLogic",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquafine/Trojan",
      },
      {
        label: "D AF",
        value: "D AF",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquionics",
      },
      {
        label: "D PH",
        value: "D PH",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquionics",
      },
      {
        label: "PMD",
        value: "PMD",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquionics",
      },
      {
        label: "PQ",
        value: "PQ",
        auto_size: "",
        frequency_family: "60Hz",
        manufacturer_model: "Aquionics",
      },
    ],
  },
  {
    label: "PROflex",
    slug: "proflexnam",
    region: "NAM",
    packagedSystemFirmProposal: true,
    model: [
      {
        label: "12-2S",
        value: "12-2S",
        auto_size: "50",
        recovery: 0.75,
        frequency_family: "60Hz",
      },
      {
        label: "18-2S",
        value: "18-2S",
        auto_size: "85",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "24-3S",
        value: "24-3S",
        auto_size: "100",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "30-2S",
        value: "30-2S",
        auto_size: "140",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "36-3S",
        value: "36-3S",
        auto_size: "160",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "36-2S",
        value: "36-2S",
        auto_size: "170",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "42-3S",
        value: "42-3S",
        auto_size: "190",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "54-3S",
        value: "54-3S",
        auto_size: "225",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "54-2S",
        value: "54-2S",
        auto_size: "255",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "72-3S",
        value: "72-3S",
        auto_size: "315",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "72-2S",
        value: "72-2S",
        auto_size: "340",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "90-2S",
        value: "90-2S",
        auto_size: "400",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
      {
        label: "108-3S",
        value: "108-3S",
        auto_size: "475",
        recovery: 0.8,
        frequency_family: "60Hz",
      },
      {
        label: "108-2S",
        value: "108-2S",
        auto_size: "500",
        recovery: 0.775,
        frequency_family: "60Hz",
      },
    ],
  },
  {
    label: "ZPakR",
    slug: "zpakr",
    region: "NAM",
    packagedSystemFirmProposal: true,
    model: [
      {
        label: "Z-PAK R-100 Master Skid",
        value: "Z-PAK R-100 Master Skid",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-Pak R-200 Master Skid",
        value: "Z-Pak R-200 Master Skid",
        auto_size: "240",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-200E Master Skid",
        value: "Z-PAK R-200E Master Skid",
        auto_size: "250",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-400 Master Skid",
        value: "Z-PAK R-400 Master Skid",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-600 Master Skid",
        value: "Z-PAK R-600 Master Skid",
        auto_size: "600",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-800 Master Skid",
        value: "Z-PAK R-800 Master Skid",
        auto_size: "800",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-1100 Master Skid",
        value: "Z-PAK R-1100 Master Skid",
        auto_size: "1100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-100 Remote Skid",
        value: "Z-PAK R-100 Remote Skid",
        auto_size: "100",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-200 Remote Skid",
        value: "Z-PAK R-200 Remote Skid",
        auto_size: "240",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-200E Remote Skid",
        value: "Z-PAK R-200E Remote Skid",
        auto_size: "250",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-400 Remote Skid",
        value: "Z-PAK R-400 Remote Skid",
        auto_size: "400",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-600 Remote Skid",
        value: "Z-PAK R-600 Remote Skid",
        auto_size: "600",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-800 Remote Skid",
        value: "Z-PAK R-800 Remote Skid",
        auto_size: "800",
        recovery: 1,
        frequency_family: "60Hz",
      },
      {
        label: "Z-PAK R-1100 Remote Skid",
        value: "Z-PAK R-1100 Remote Skid",
        auto_size: "1100",
        recovery: 1,
        frequency_family: "60Hz",
      },
    ],
  },
];
